#!/usr/bin/env python3

import RPi.GPIO as GPIO
import time

GPIO.setmode(GPIO.BCM)
GPIO.setup(22, GPIO.OUT)

GPIO.setmode(GPIO.BCM)
GPIO.setup(4, GPIO.OUT)

GPIO.setmode(GPIO.BCM)
GPIO.setup(6, GPIO.OUT)

GPIO.setmode(GPIO.BCM)
GPIO.setup(19, GPIO.OUT)

while True:
   GPIO.output(19, 1)
   time.sleep(.1)
   GPIO.output(19, 0)
   GPIO.output(6, 1)
   time.sleep(.1)
   GPIO.output(6, 0)
   GPIO.output(22, 1)
   time.sleep(.1)
   GPIO.output(22, 0)
   GPIO.output(4, 1)
   time.sleep(.1)
   GPIO.output(4, 0)
   time.sleep(.1)
GPIO.cleanup()
